### ISSUE TITLE
README For The Application

### ISSUE THREAD

**Issue by Michael-Seth** [paigexx/pinniebox_backend#1]
Hi PaigeXX, can you write a readme for this application, I am currently learning go and I will like to clone this project and build with you. I want to know what this app is about, how it is to be used and how I can contribute.
Thank you.

**Comment by paigexx** [comment]
Hey @Michael-Seth, I've added a short read me. I'm not looking for contributions at this time but feel free to let me know if you have any questions with the repository. Thanks
